--- #YAML:1.0
name:               String-CaseProfile
version:            0.18
abstract:           Get/Set the letter case profile of a string
author:
    - Enrique Nell <perl_nell@telefonica.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::Warn:  0.05
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
